server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    #telemetry-simulator
    location /api/fleet {
        proxy_pass http://telemetry-simulator:8091/fleet;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    #telemetry-services
    location /api/control {
        proxy_pass http://telemetry-services:8092/control;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # FONDAMENTALE per i Server-Sent Events (Flux / SSE)
        # Disabilita il buffering per evitare che Nginx trattenga i dati in streaming
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;
        
        # Timeout prolungati per evitare che la connessione SSE cada per inattività
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Gestione delle rotte di Angular (SPA routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache opzionale per i file statici (immagini, JS, CSS)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}